paths:
  /api/products/:
    #getProducts
    get:
      summary: get all products
      tags:
        - products
      responses:
        200:
          description: the products were successfully received
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        500:
          description: problem on the server
          content:
            application/json:
              schema:
                $ref: "#components/schemas/getError"

    #add product
    post:
      summary: add product
      tags:
        - products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/addUpdateProduct"
      responses:
        200:
          description: product added successfully
          content:
            application/json:
              schema:
                $ref: "#components/schemas/addSuccess"
        500:
          description: problem on the server
          content:
            application/json:
              schema:
                $ref: "#components/schemas/addError"

  #ID
  /api/products/{pid}:
    #get product by ID
    get:
      summary: get a product by id
      tags:
        - products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID of the product to consult
          schema:
            $type: string
      responses:
        200:
          description: the product were successfully received
          content:
            application/json:
              schema:
                $ref: "#components/schemas/products"
        500:
          description: problem on the server
          content:
            application/json:
              schema:
                $ref: "#components/schemas/getError"

    #update product
    put:
      summary: update product information
      tags:
        - products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID of the product to update
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/addUpdateProduct"

      responses:
        200:
          description: the product were successfully updated
          content:
            application/json:
              schema:
                $ref: "#components/schemas/updateSuccess"
        500:
          description: problem on the server
          content:
            application/json:
              schema:
                $ref: "#components/schemas/updateError"

    #delete product
    delete:
      summary: remove the product
      tags:
        - products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID of the product to remove
          schema:
            $type: string

      responses:
        200:
          description: the product were successfully removed
          content:
            application/json:
              schema:
                $ref: "#components/schemas/deleteSuccess"
        500:
          description: problem on the server
          content:
            application/json:
              schema:
                $ref: "#components/schemas/deleteError"

components:
  schemas:
    #schema de producto
    products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id generated by Mongo DB
        title:
          type: string
          description: Product name
        description:
          type: string
          description: Product description
        price:
          type: number
          description: Product price
        code:
          type: string
          description: Product unique code
        stock:
          type: number
          description: Quantity of products in stock
        status:
          type: boolean
          description: Product status
        category:
          type: string
          description: Indicates whether the product belongs to the category full, top or bottom
        thumbnail:
          type: string
          description: Product image link
        __v:
          type: number
          description: MongoDB autogenerated property used to store the number of versions of a document
        owner:
          type: ObjectId
          description: Id generated by Mongo DB of the user who crated the product

      example:
        _id: "651dce32ba3fb57af20c9008"
        title: "Sky Skirt"
        description: "Denim skirt with front pockets"
        price: 11000
        code: "PROD3"
        stock: 0
        status: true
        category: "bottom"
        thumbnail: "https://res.cloudinary.com/dqrgdohtt/image/upload/v1687800306/skySkirt_dkuofw.jpg"
        __v: 0
        owner: "6564ea0d913aa2774e9e2ea6"

    #update product success
    updateSuccess:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data: object
      example:
        status: success
        message: product updated successfully
        data:
          _id: "651dce32ba3fb57af20c9008"
          title: "Sky Skirt"
          description: "Denim skirt with front pockets"
          price: 11000
          code: "PROD3"
          stock: 0
          status: true
          category: "bottom"
          thumbnail: "https://res.cloudinary.com/dqrgdohtt/image/upload/v1687800306/skySkirt_dkuofw.jpg"
          __v: 0
          owner: "6564ea0d913aa2774e9e2ea6"

    #add product success
    addSuccess:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      example:
        status: success
        message: sky skirt added successfully!

    #delete product success
    deleteSuccess:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      example:
        status: success
        message: sky skirt removed successfully!

    #get products error
    getError:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      example:
        status: error
        message: error getting the products

    #add products error
    addError:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      example:
        status: error
        message: error adding the product

    #update product error
    updateError:
      type: object
      properties:
        status:
          type: string
          message:
            type: string
            example:
              status: error
              message: error updating the product

    #delete product error
    deleteError:
      type: object
      properties:
        status:
          type: string
          message:
            type: string
            example:
              status: error
              message: error deleting the product

  requestBodies:
    addUpdateProduct:
      type: object
      properties:
        title:
          type: string
          description: Product name
        description:
          type: string
          description: Product description
        price:
          type: number
          description: Product price
        code:
          type: string
          description: Product unique code
        stock:
          type: number
          description: Quantity of products in stock
        status:
          type: boolean
          description: Product status
        category:
          type: string
          description: Indicates whether the product belongs to the category full, top or bottom
        thumbnail:
          type: string
          description: Product image link

      example:
        title: "Sky Skirt"
        description: "Denim skirt with front pockets"
        price: 11000
        code: "PROD3"
        stock: 0
        status: true
        category: "bottom"
        thumbnail: "https://res.cloudinary.com/dqrgdohtt/image/upload/v1687800306/skySkirt_dkuofw.jpg"
